import { createContext, useContext, useMemo, useState } from 'react'

export const LANGUAGES = {
  en: { label: 'English', nativeLabel: 'English' },
  hi: { label: 'Hindi', nativeLabel: 'हिन्दी' },
  mr: { label: 'Marathi', nativeLabel: 'मराठी' },
  ta: { label: 'Tamil', nativeLabel: 'தமிழ்' },
}

const TRANSLATIONS = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Analytics',
    'nav.transactions': 'Transactions',
    'nav.bills': 'Bill Payments',
    'nav.rewards': 'Rewards',
    'nav.referral': 'Refer & Earn',
    'nav.send': 'Send Money',
    'nav.request': 'Request Money',
    'nav.balance': 'Check Balance',
    'nav.qr': 'QR Scanner',
    'nav.split': 'Split Payment',
    'nav.scheduled': 'Scheduled Payments',
    'nav.feedback': 'Feedback',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.mainMenu': 'Main Menu',
    'nav.account': 'Account',
    'app.tagline': 'Smart Payments',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.language': 'Language',
    'settings.languageHelp': 'Choose the language used for primary PayFlow screens.',
    'settings.languageApplied': 'Language updated',
    'rewards.title': 'Rewards',
    'rewards.subtitle': 'Earn points on every transaction',
    'rewards.totalPoints': 'Total Points Balance',
    'rewards.points': 'pts',
    'rewards.tiers': 'Loyalty Tiers',
    'rewards.benefits': 'Tier Benefits',
    'rewards.dailyBonus': 'Daily Bonus',
    'rewards.dailyCopy': 'Log in every day to earn your daily bonus.',
    'rewards.claim': 'Claim Daily Bonus (+50 pts)',
    'rewards.claimed': 'Bonus Claimed Today',
    'rewards.comeBack': 'Come back tomorrow for your next bonus!',
    'rewards.howEarn': 'How to Earn',
    'rewards.cashback': 'Cashback Offers',
    'rewards.history': 'Points History',
    'rewards.noHistory': 'No reward history yet. Start earning!',
    'rewards.toNext': 'pts to',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.analytics': 'विश्लेषण',
    'nav.transactions': 'लेन-देन',
    'nav.bills': 'बिल भुगतान',
    'nav.rewards': 'रिवॉर्ड्स',
    'nav.referral': 'रेफर करें',
    'nav.send': 'पैसे भेजें',
    'nav.request': 'पैसे मांगें',
    'nav.balance': 'बैलेंस देखें',
    'nav.qr': 'QR स्कैनर',
    'nav.split': 'स्प्लिट भुगतान',
    'nav.scheduled': 'शेड्यूल भुगतान',
    'nav.feedback': 'फीडबैक',
    'nav.notifications': 'सूचनाएं',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉगआउट',
    'nav.mainMenu': 'मुख्य मेनू',
    'nav.account': 'खाता',
    'app.tagline': 'स्मार्ट भुगतान',
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपना खाता और पसंद प्रबंधित करें',
    'settings.language': 'भाषा',
    'settings.languageHelp': 'मुख्य PayFlow स्क्रीन के लिए भाषा चुनें।',
    'settings.languageApplied': 'भाषा अपडेट हो गई',
    'rewards.title': 'रिवॉर्ड्स',
    'rewards.subtitle': 'हर लेन-देन पर पॉइंट कमाएं',
    'rewards.totalPoints': 'कुल पॉइंट बैलेंस',
    'rewards.points': 'पॉइंट',
    'rewards.tiers': 'लॉयल्टी टियर',
    'rewards.benefits': 'टियर लाभ',
    'rewards.dailyBonus': 'दैनिक बोनस',
    'rewards.dailyCopy': 'दैनिक बोनस पाने के लिए रोज लॉग इन करें।',
    'rewards.claim': 'दैनिक बोनस लें (+50 पॉइंट)',
    'rewards.claimed': 'आज का बोनस मिल गया',
    'rewards.comeBack': 'अगले बोनस के लिए कल वापस आएं!',
    'rewards.howEarn': 'कैसे कमाएं',
    'rewards.cashback': 'कैशबैक ऑफर',
    'rewards.history': 'पॉइंट इतिहास',
    'rewards.noHistory': 'अभी कोई रिवॉर्ड इतिहास नहीं। कमाना शुरू करें!',
    'rewards.toNext': 'पॉइंट बाकी',
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.analytics': 'विश्लेषण',
    'nav.transactions': 'व्यवहार',
    'nav.bills': 'बिल भरणा',
    'nav.rewards': 'रिवॉर्ड्स',
    'nav.referral': 'रेफर करा',
    'nav.send': 'पैसे पाठवा',
    'nav.request': 'पैसे मागा',
    'nav.balance': 'बॅलन्स तपासा',
    'nav.qr': 'QR स्कॅनर',
    'nav.split': 'स्प्लिट पेमेंट',
    'nav.scheduled': 'नियोजित पेमेंट',
    'nav.feedback': 'फीडबॅक',
    'nav.notifications': 'सूचना',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉगआउट',
    'nav.mainMenu': 'मुख्य मेनू',
    'nav.account': 'खाते',
    'app.tagline': 'स्मार्ट पेमेंट्स',
    'settings.title': 'सेटिंग्ज',
    'settings.subtitle': 'तुमचे खाते आणि पसंती व्यवस्थापित करा',
    'settings.language': 'भाषा',
    'settings.languageHelp': 'मुख्य PayFlow स्क्रीनसाठी भाषा निवडा.',
    'settings.languageApplied': 'भाषा अपडेट झाली',
    'rewards.title': 'रिवॉर्ड्स',
    'rewards.subtitle': 'प्रत्येक व्यवहारावर पॉइंट्स कमवा',
    'rewards.totalPoints': 'एकूण पॉइंट बॅलन्स',
    'rewards.points': 'पॉइंट्स',
    'rewards.tiers': 'लॉयल्टी स्तर',
    'rewards.benefits': 'स्तर फायदे',
    'rewards.dailyBonus': 'दैनिक बोनस',
    'rewards.dailyCopy': 'दैनिक बोनससाठी रोज लॉग इन करा.',
    'rewards.claim': 'दैनिक बोनस घ्या (+50 पॉइंट्स)',
    'rewards.claimed': 'आजचा बोनस मिळाला',
    'rewards.comeBack': 'पुढील बोनससाठी उद्या या!',
    'rewards.howEarn': 'कसे कमवाल',
    'rewards.cashback': 'कॅशबॅक ऑफर्स',
    'rewards.history': 'पॉइंट इतिहास',
    'rewards.noHistory': 'अजून रिवॉर्ड इतिहास नाही. कमावायला सुरुवात करा!',
    'rewards.toNext': 'पॉइंट्स बाकी',
  },
  ta: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.transactions': 'பரிவர்த்தனைகள்',
    'nav.bills': 'பில் கட்டணம்',
    'nav.rewards': 'ரிவார்ட்ஸ்',
    'nav.referral': 'பரிந்துரை',
    'nav.send': 'பணம் அனுப்பு',
    'nav.request': 'பணம் கோரு',
    'nav.balance': 'இருப்பு பார்க்க',
    'nav.qr': 'QR ஸ்கேனர்',
    'nav.split': 'பகிர்ந்த கட்டணம்',
    'nav.scheduled': 'திட்டமிட்ட கட்டணம்',
    'nav.feedback': 'கருத்து',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    'nav.mainMenu': 'முதன்மை மெனு',
    'nav.account': 'கணக்கு',
    'app.tagline': 'ஸ்மார்ட் கட்டணங்கள்',
    'settings.title': 'அமைப்புகள்',
    'settings.subtitle': 'உங்கள் கணக்கும் விருப்பங்களும்',
    'settings.language': 'மொழி',
    'settings.languageHelp': 'முக்கிய PayFlow திரைகளுக்கான மொழியை தேர்வு செய்யவும்.',
    'settings.languageApplied': 'மொழி புதுப்பிக்கப்பட்டது',
    'rewards.title': 'ரிவார்ட்ஸ்',
    'rewards.subtitle': 'ஒவ்வொரு பரிவர்த்தனையிலும் பாயிண்ட்ஸ் பெறுங்கள்',
    'rewards.totalPoints': 'மொத்த பாயிண்ட் இருப்பு',
    'rewards.points': 'பாயிண்ட்ஸ்',
    'rewards.tiers': 'லாயல்டி நிலைகள்',
    'rewards.benefits': 'நிலை நன்மைகள்',
    'rewards.dailyBonus': 'தினசரி போனஸ்',
    'rewards.dailyCopy': 'தினசரி போனஸுக்கு ஒவ்வொரு நாளும் உள்நுழையவும்.',
    'rewards.claim': 'தினசரி போனஸ் பெறுங்கள் (+50 பாயிண்ட்ஸ்)',
    'rewards.claimed': 'இன்றைய போனஸ் பெறப்பட்டது',
    'rewards.comeBack': 'அடுத்த போனஸுக்கு நாளை வாருங்கள்!',
    'rewards.howEarn': 'எப்படி பெறுவது',
    'rewards.cashback': 'கேஷ்பேக் சலுகைகள்',
    'rewards.history': 'பாயிண்ட் வரலாறு',
    'rewards.noHistory': 'இன்னும் ரிவார்ட்ஸ் வரலாறு இல்லை. பெறத் தொடங்குங்கள்!',
    'rewards.toNext': 'பாயிண்ட்ஸ் மீதம்',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('payflow_language') || 'en')

  const changeLanguage = (nextLanguage) => {
    const safeLanguage = LANGUAGES[nextLanguage] ? nextLanguage : 'en'
    setLanguage(safeLanguage)
    localStorage.setItem('payflow_language', safeLanguage)
  }

  const value = useMemo(() => ({
    language,
    languages: LANGUAGES,
    changeLanguage,
    t: (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key,
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
