spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/payflow?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3&verifyServerCertificate=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:25HE5HDop1m3srh.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sRZ3tki5T3Pkhm7d}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
