spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql311.infinityfree.com:3306/if0_41999902_PayFlowDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:if0_41999902}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2Bx9Ct24RKKDVsz}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
