spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/payflow?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:25HE5HDop1m3srh.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:V4I2nmt77Kt9YxAy}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}
